### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by hannesa2** [farmaker47/Diffusion_models_app#3]
After I enabled arm64 to run on my Apple Silicon emulator and copy tflite I run into
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/3314607/219032483-f35b8f27-1728-4ac4-913c-b2a43baf4512.png">

so you have any idea ?

**Comment by hannesa2** [comment]
I changes logging, to see immediate, from where the log comes from.
(Now you can click and jump immediate to code line)
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/3314607/219035577-e21d9edf-2590-44af-8ad2-4d39ea1ba233.png">

But what's the reason of this ?

`ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by hannesa2** [comment]
I'm just guessing: Does `run_diffusion_model.py` comes with an error ?

```
E/(DiffusionExecutor.kt:405) .encoderExecutor(): com.chaquo.python.PyException: ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
        at <python>.requests.adapters.send(adapters.py:547)
        at <python>.requests.sessions.send(sessions.py:701)
        at <python>.requests.sessions.request(sessions.py:587)
        at <python>.requests.api.request(api.py:59)
        at <python>.requests.api.post(api.py:115)
        at <python>.run_diffusion_model.runDiffusionModel(run_diffusion_model.py:18)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at <python>.requests.sessions.request(sessions.py:587)
        at <python>.requests.api.request(api.py:59)
        at <python>.requests.api.post(api.py:115)
        at <python>.run_diffusion_model.runDiffusionModel(run_diffusion_model.py:18)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.diffusionmodelsapp.ui.main.DiffusionExecutor.encoderExecutor(DiffusionExecutor.kt:372)
        at com.example.diffusionmodelsapp.ui.main.MainViewModel.getResult(MainViewModel.kt:11)
        at com.example.diffusionmodelsapp.ui.main.MainFragment$onCreateView$1$1.invokeSuspend(MainFragment.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

**Comment by farmaker47** [comment]
It takes too much time to fetch the result and it closes the connection.
1. Try to see at Colab that you are on GPU or
2. Lower the number of steps from 25 to below 4 at Colab to get a result. This will have an impact to the final quality of the image though.

**Comment by hannesa2** [comment]
> * Try to see at Colab that you are on GPU or

No clue how to do this

> * Lower the number of steps from 25 to below 4 at Colab to get a result. This will have an impact to the final quality of the image though.

Error till exists
<img width="435" alt="image" src="https://user-images.githubusercontent.com/3314607/219045228-bfa57a83-5c77-4536-886e-c7a342cb12dd.png">

**Comment by farmaker47** [comment]
Have you opened and run Colab from top to bottom? This is a prerequisite to get the result. It is at the first lines of the README file.
Are you familiar with Colab, or python? You have to run the notebook, get the address and paste it inside the android project.
